# Generated by Django 2.2.10 on 2020-03-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cases', models.CharField(max_length=300)),
                ('new_cases', models.CharField(max_length=300)),
                ('total_deaths', models.CharField(max_length=300)),
                ('new_deaths', models.CharField(max_length=300)),
                ('active_cases', models.CharField(max_length=300)),
                ('total_recovered', models.CharField(max_length=300)),
                ('serious_critical', models.CharField(max_length=300)),
            ],
        ),
    ]
